### ISSUE TITLE
request_project.py adds to but does not delete organisms from the database

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/tripal_tests#1]
request_project.py should add a function that deletes the created organism from the database. Screenshot of content list on prod: 

![Screen Shot 2019-08-06 at 14 43 07](https://user-images.githubusercontent.com/5487172/62575698-918bc580-b858-11e9-825a-8ec5df38a2c4.png)

Might be good to disable the test until this is updated.

**Comment by childers** [comment]
This should be fixed.
